AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false


Layout/HashAlignment:
  # Align the elements of a hash literal if they span more than one line.
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Layout/LineLength:
#   # Checks that line length does not exceed the configured limit.
#   Max: 150


Lint/DuplicateBranch:
  # Checks that there are no repeated bodies within `if/unless`, `case-when` and `rescue` constructs.
  Enabled: false


Metrics/AbcSize:
  # A calculated magnitude based on number of assignments, branches, and conditions.
  Max: 30

Metrics/BlockLength:
  # Avoid long blocks with many lines.
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  # A complexity metric that is strongly correlated to the number of test cases needed to validate a method.
  Max: 10

Metrics/MethodLength:
  # Avoid methods longer than 25 lines of code.
  Max: 25


Style/ClassAndModuleChildren:
  # Checks style of children classes and modules.
  Enabled: false

Style/FetchEnvVar:
  # Suggests `ENV.fetch` for the replacement of `ENV[]`.
  Enabled: false

Style/FormatString:
  # Enforce the use of Kernel#sprintf, Kernel#format or String#%.
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  # Enforces use of the frozen_string_literal comment in every file.
  EnforcedStyle: never

Style/NumericLiterals:
  # Add underscores to large numeric literals to improve their readability.
  Enabled: false

Style/PreferredHashMethods:
  # Checks use of `has_key?` and `has_value?` Hash methods.
  EnforcedStyle: verbose

Style/RegexpLiteral:
  # Use / or %r around regular expressions.
  EnforcedStyle: percent_r

Style/RescueModifier:
  # Avoid using rescue in its modifier form.
  Enabled: false

Style/StringLiterals:
  # Check for use of ' vs ".
  ConsistentQuotesInMultiline: true
